// global-variables.tsZ
import { Order } from "src/app/Model/Order";

export const GlobalVariables = {
  order: <Order>{
    id: undefined,
    product: undefined,
    paper: undefined,
    sizeCategory: undefined,
    size: undefined,
    gsm: undefined,
    quantity: undefined,
    amount: undefined,
    jobColorsFront: undefined,
    sideOptionValue: undefined,
    impositionValue: undefined,
    jobColorsBack: undefined,
    providedDesign: undefined,
    url: undefined,
    productRule: undefined,
    status: undefined,
    type: undefined,
    ctpProcess: undefined,
    pressMachineProcess: undefined,
    paperMarketProcess: undefined,
    designer: undefined,
    production: undefined,
    plateSetter: undefined,
    isRejected: false,
    timeStamp: undefined,
    createdBy: undefined,
    assignedBy: undefined,
    customer: undefined,
    businessCategory: undefined,
    productionUser: undefined,
    titleId: undefined,
    jobId: undefined,
    productCategory: undefined,
    description: undefined,
    rate: undefined,
    linkedInvoice: undefined,
    privateNotes: undefined,
    orderTrackingNotes: undefined,
    productionNotes: undefined,
    ctpFileName: undefined,
    locationOfFile: undefined,
    sentOn: undefined,
    designPackageFile: undefined,
    locationOfDesignFile: undefined,
    jobStartDate: undefined,
    productionStartDate: undefined,
    productionEndDate: undefined,
    packingAndQADate: undefined,
    deliveryDate: undefined,
    expiryDate: undefined,
    sendTo: undefined,
    processedDetailList: [],
    businesses:[],
  }
};
