import { Timestamp } from "rxjs";
import { Business } from "./Business";
import { BusinessUnitProcessDto } from "./BusinessUnit";
import { Customer } from "./Customer";
import { JobProcessedDetails } from "./ProcessDetails";
import { User } from "./User";

export interface Order {
  id: number | undefined | null;
  product: string | undefined | null;
  paper: string | undefined | null;
  sizeCategory: string | undefined | null;
  size: string | undefined | null;
  gsm: number | undefined | null;
  quantity: number | undefined | null;
  amount: number | undefined | null;
  jobColorsFront: number | undefined | null;
  sideOptionValue: string | undefined | null;
  impositionValue: boolean | undefined | null;
  jobColorsBack: number | undefined | null;
  providedDesign: boolean | undefined | null;
  url: string | undefined | null;
  productRule: number | undefined | null;
  status: string | undefined | null;
  type: string | undefined | null;
  ctpProcess: boolean | undefined | null;
  pressMachineProcess: boolean | undefined | null;
  paperMarketProcess: boolean | undefined | null;
  designer: User | undefined | null;
  production: User | undefined | null;
  plateSetter: User | undefined | null;
  isRejected: boolean;
  timeStamp: Date | string | undefined | null | [number, number, number, number, number, number, number];
  createdBy: User | undefined | null;
  assignedBy: User | undefined | null;
  customer: Customer | undefined | null;
  businessCategory: string | undefined | null;
  businesses?: Business[];
  productionUser: string | undefined | null;
  titleId: number | undefined | null;
  jobId: string | undefined | null;
  productCategory: any;
  description: string | undefined | null;
  rate: number | undefined | null;
  linkedInvoice: string | undefined | null;
  privateNotes: string | undefined | null;
  orderTrackingNotes: string | undefined | null;
  productionNotes: string | undefined | null;
  ctpFileName: string | undefined | null;
  locationOfFile: string | undefined | null;
  sentOn: Date | undefined | null;
  designPackageFile: string | undefined | null;
  locationOfDesignFile: string | undefined | null;
  jobStartDate: Date | undefined | null;
  productionStartDate: Date | undefined | null;
  productionEndDate: Date | undefined | null;
  packingAndQADate: Date | undefined | null;
  deliveryDate: Date | undefined | null;
  expiryDate: Date | undefined | null;
  sendTo: string | undefined | null;
  orderItems?: OrderItem[];
  processedDetailList: JobProcessedDetails[];
  processList?: BusinessUnitProcessDto[];
}
export interface OrderItem {
  id: number | undefined | null;
  name: string | undefined | null;
  quantity: number | undefined | null;
}